site_name: Zettlr Docs
site_url: https://docs.zettlr.com/ja
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Zettlrを最大限活用するために必要となる、あらゆる情報を提供するドキュメンテーションです。
site_author: Hendrik Erz
copyright: "&copy; 2017-2019 by Zettlr"
docs_dir: ../docs/ja
site_dir: ../build/ja
edit_uri: edit/master/docs/ja
extra_css:
  - assets/app.css
nav:
  - はじめに: index.md
  - インストール: install.md
  - クイックスタート: 5-minutes.md
  - ユーザーガイド:
    - Zettlrでノートを取る: guides/guide-notes.md
    - ZettlrをZettelkastenシステムとして使う: guides/guide-zettelkasten.md
    - ZettlrをIDEとして使う: guides/guide-ide.md
  - 主要機能:
    - エディタ: core/editor.md
    - ファイルリスト: core/file-list.md
    - 検索: core/search.md
    - エクスポート: core/export.md
    - テーブル編集: core/tables.md
    - 仮想ディレクトリ: core/virtual-directories.md
    - カスタムCSS: core/custom-css.md
    - ローカライゼーション: core/localisation.md
    - 添付ファイルサイドバー: core/attachments.md
  - 学術ツール:
    - 参考文献: academic/citations.md
    - プロジェクト: academic/projects.md
    - プレゼンテーション: academic/presentations.md
    - ポモドーロタイマー: academic/pomodoro.md
    - 可読性: academic/readability.md
    - Zettelkastenメソッド: academic/zkn-method.md
    - カスタムテンプレート: academic/custom-templates.md
  - 参考資料:
    - ショートカット: reference/shortcuts.md
    - マークダウンの基本: reference/markdown-basics.md
    - 設定: reference/settings.md
    - スペルチェック: reference/spell-checking.md
  - ご協力ください: get-involved.md
  - FAQ: faq.md
theme:
  name: readthedocs
  custom_dir: ../theme_override
  highlightjs: True
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - css
    - yaml
    - tex
markdown_extensions:
    - toc:
        permalink: True
plugins:
  - search:
      lang: jp
