site_name: Zettlr Docs
site_url: https://docs.zettlr.com/ja
repo_url: https://github.com/Zettlr/zettlr-docs
site_description: >-
    Zettlrを最大限活用するために必要となる、あらゆる情報を提供するドキュメンテーションです。
site_author: Hendrik Erz
copyright: "&copy; 2017-2019 by Zettlr"
docs_dir: ../docs/ja
site_dir: ../build/ja
edit_uri: edit/master/docs/ja
extra_css:
  - assets/app.css
nav:
  - Welcome: index.md
  - Setup: install.md
  - Quick Start: 5-minutes.md
  - Guides:
    - Zettlr as a note taking app: guides/guide-notes.md
    - Zettlr as a Zettelkasten: guides/guide-zettelkasten.md
    - Zettlr as an IDE: guides/guide-ide.md
  - Core:
    - The Editor: core/editor.md
    - The File List: core/file-list.md
    - Searching: core/search.md
    - Exporting: core/export.md
    - Table Editor: core/tables.md
    - Virtual Directories: core/virtual-directories.md
    - Custom CSS: core/custom-css.md
    - Localisation: core/localisation.md
    - Attachment Sidebar: core/attachments.md
  - Academic Tools:
    - Citations: academic/citations.md
    - Projects: academic/projects.md
    - Presentations: academic/presentations.md
    - Pomodoro Timer: academic/pomodoro.md
    - Readability: academic/readability.md
    - Zettelkasten Methods: academic/zkn-method.md
    - Custom Templates: academic/custom-templates.md
  - References:
    - Shortcuts: reference/shortcuts.md
    - Markdown Basics: reference/markdown-basics.md
    - Settings: reference/settings.md
    - Spell Checking: reference/spell-checking.md
  - Get involved: get-involved.md
  - FAQ: faq.md
theme:
  name: readthedocs
  custom_dir: ../theme_override
  highlightjs: True
  prev_next_buttons_location: both
  hljs_languages:
    - javascript
    - css
    - yaml
    - tex
markdown_extensions:
    - toc:
        permalink: True
plugins:
  - search:
      lang: ja
